### ISSUE TITLE
xrdcp stdout and stderr needs to be sent to stdout

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/func_adl_cache#4]
There are some copy failures that I do not yet understood (see below). Seems to happen with lots of requests.

Once that works, we might need to add retry to this guy.

```
Run: [ERROR] Server responded with an error: [3006] File exists

[2019-07-14 21:50:51 +0000] [843] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 124, in run
    self.run_for_one(timeout)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)                                                                                                 File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 30, in accept                                self.handle(listener, client, addr)                                                                                   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle                               self.handle_request(listener, req, client, addr)                                                                      File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request                       respiter = self.wsgi(environ, resp.start_response)                                                                    File "/usr/local/lib/python3.6/site-packages/hug/api.py", line 497, in api_auto_instantiate                               return module.__hug_wsgi__(*args, **kwargs)                                                                           File "falcon/api.py", line 269, in falcon.api.API.__call__                                                              File "/usr/local/lib/python3.6/site-packages/hug/interface.py", line 901, in __call__                                     self.call_function(input_parameters), context, request, response, **kwargs                                            File "/usr/local/lib/python3.6/site-packages/hug/interface.py", line 823, in call_function                                return self.interface(**parameters)                                                                                   File "/usr/local/lib/python3.6/site-packages/hug/interface.py", line 123, in __call__                                     return __hug_internal_self._function(*args, **kwargs)                                                                 File "/home/cacher/query.py", line 108, in query                                                                          result = fetch_data(a, local_cache_item_dir)                                                                          File "/home/cacher/query.py", line 67, in fetch_data                                                                      raise CacheCopyError(f'Failed to copy file {url} to {final_location}.')                                             query.CacheCopyError: Failed to copy file root://charm.epe.phys.washington.edu:30001//7af9fefc0ca3e90e85e1e12abc2ea781/ANALYSIS_001.root to /cache/7af9fefc0ca3e90e85e1e12abc2ea781/ANALYSIS_001.root.                                          [2019-07-14 21:50:51 +0000] [843] [INFO] Worker exiting (pid: 843) 
```

**Comment by gordonwatts** [comment]
Re-running this, btw, and it works. So whatever the problem is, it is intermittent.

**Comment by gordonwatts** [comment]
There is nothing obvious in the xrootd logs. I wonder if this is another windows file-system problem?
