### ISSUE TITLE
When a server error occurs at the remote point, make sure error includes message

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/func_adl_cache#8]
Currently local log file has nothing about what caused the error for parsing json:

```
INFO:root:Requesting data from http://charm.epe.phys.washington.edu:30000/query                                         [2019-08-29 13:13:45 +0000] [119] [ERROR] Error handling request /query
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/hug/api.py", line 497, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/usr/local/lib/python3.6/site-packages/hug/interface.py", line 930, in __call__
    raise exception
  File "/usr/local/lib/python3.6/site-packages/hug/interface.py", line 901, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/usr/local/lib/python3.6/site-packages/hug/interface.py", line 823, in call_function
    return self.interface(**parameters)
  File "/usr/local/lib/python3.6/site-packages/hug/interface.py", line 123, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/cacher/query.py", line 186, in query
    result = json.load(o)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by gordonwatts** [comment]
The above seems to happen for all new requests right now! Ugh! :-)

**Comment by gordonwatts** [comment]
Note this occurs in line 186 - that is something that loads a previously parsed file! WTF, as they say! So it parsed just fine previously, but now it no longer parses correctly. This is some sort of weird race condition?

Basically: this should never occur!
